# Generated by Django 4.2.10 on 2024-05-15 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('add_date', models.DateField(blank=True, null=True)),
                ('plant_type', models.CharField(max_length=10)),
                ('plant_name', models.CharField(blank=True, max_length=30, null=True)),
                ('plant_size', models.CharField(blank=True, max_length=30, null=True)),
                ('plant_color', models.CharField(blank=True, max_length=30, null=True)),
                ('plant_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('plant_picture', models.ImageField(default='default/default_plant.png', upload_to='plants/')),
            ],
            options={
                'db_table': 'plant',
            },
        ),
        migrations.CreateModel(
            name='Annual',
            fields=[
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.plant')),
                ('is_hardy', models.BooleanField(blank=True, null=True)),
                ('is_semi_hardy', models.BooleanField(blank=True, null=True)),
                ('shade_tolerant', models.BooleanField(blank=True, null=True)),
                ('heat_tolerant', models.BooleanField(blank=True, null=True)),
                ('drought_tolerant', models.BooleanField(blank=True, null=True)),
                ('annual_category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'annual',
            },
        ),
        migrations.CreateModel(
            name='Perennial',
            fields=[
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.plant')),
                ('light_code', models.CharField(blank=True, max_length=30, null=True)),
                ('moisture_level', models.CharField(blank=True, max_length=30, null=True)),
                ('care_level', models.CharField(blank=True, max_length=30, null=True)),
                ('perennial_category', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'perennial',
            },
        ),
        migrations.CreateModel(
            name='Shrub',
            fields=[
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.plant')),
                ('shrub_category', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'shrub',
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.plant')),
                ('tree_category', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'tree',
            },
        ),
    ]
