# Generated by Django 4.2.10 on 2024-05-15 18:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='add_date',
            field=models.DateField(default=datetime.date(2024, 5, 15)),
        ),
        migrations.AlterField(
            model_name='plant',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.department'),
        ),
    ]
