# Generated by Django 4.2.10 on 2024-05-15 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_password', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_email', models.CharField(blank=True, max_length=30, null=True)),
                ('employee_first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('employee_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('employee_password', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_admin', models.CharField(blank=True, max_length=1, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.department')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('search_id', models.AutoField(primary_key=True, serialize=False)),
                ('search_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.plant')),
            ],
            options={
                'db_table': 'search_history',
            },
        ),
        migrations.CreateModel(
            name='QuestionsAsked',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_answered', models.BooleanField(default=False)),
                ('question_date', models.DateField(blank=True, null=True)),
                ('question', models.CharField(blank=True, max_length=1000, null=True)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('answer_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.employee')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.plant')),
            ],
            options={
                'db_table': 'questions_asked',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLogin',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_token', models.CharField(max_length=400)),
                ('date', models.DateField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employee')),
            ],
            options={
                'db_table': 'employee_login_history',
            },
        ),
        migrations.CreateModel(
            name='CustomerLogin',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_token', models.CharField(max_length=400)),
                ('date', models.DateField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
            ],
            options={
                'db_table': 'customer_login_history',
            },
        ),
    ]
