# Generated by Django 4.2.10 on 2024-02-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customer_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_password',
            field=models.CharField(blank=True, null=True),
        ),
    ]
