# Generated by Django 4.2.10 on 2024-03-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_department_department_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterModelTable(
            name='customerlogin',
            table='login_history',
        ),
    ]
