# Generated by Django 4.2.10 on 2024-03-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_employee_employee_email_alter_customerlogin_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_password',
            field=models.CharField(blank=True, null=True),
        ),
    ]
