# Generated by Django 4.2.10 on 2024-04-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_questionsasked_answer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsasked',
            name='answer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionsasked',
            name='question_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
