# Generated by Django 4.2.10 on 2024-04-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_questionsasked_answer_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsasked',
            name='answer_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
