# Generated by Django 4.2.10 on 2024-04-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_questionsasked_answer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsasked',
            name='question_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
