# Generated by Django 4.2.10 on 2024-04-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_questionsasked_question_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsasked',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
